/**
 * Regenerates the bundled catalog from a local copy of the upstream dataset:
 *
 *   src/data/catalogIndex.ts        search index (names, muscles, equipment)
 *   src/data/catalogDescriptions.ts English instruction texts
 *
 * Both ship inside main.js. Obsidian only downloads main.js, manifest.json and
 * styles.css from a release, so a separate data file would never reach anyone
 * installing from the community directory.
 *
 * Each is emitted as a JSON *string* constant rather than an object literal:
 * the bundler and JS engine treat it as a single token instead of parsing ~1300
 * nested objects at load, and JSON.parse runs once, lazily, on first use.
 *
 *   node scripts/build-catalog.mjs path/to/exercises.json
 *
 * Upstream: https://github.com/hasaneyldrm/exercises-dataset (data: MIT)
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const source = process.argv[2] ?? "vendor/exercises.json";
const records = JSON.parse(readFileSync(source, "utf8"));

/** Repairs the handful of mojibake names upstream ("sled 45в° leg press"). */
const fixName = (name) => name.replace(/в°/g, "°").replace(/\s+/g, " ").trim();

const dict = (values) => [...new Set(values)].sort();
const bodyParts = dict(records.map((r) => r.body_part ?? ""));
const equipment = dict(records.map((r) => r.equipment ?? ""));
const muscles = dict(records.flatMap((r) => [r.target ?? "", ...(r.secondary_muscles ?? [])]));

const idx = (list) => new Map(list.map((v, i) => [v, i]));
const bIdx = idx(bodyParts);
const eIdx = idx(equipment);
const mIdx = idx(muscles);

const rows = records.map((r) => [
  r.id,
  fixName(r.name),
  bIdx.get(r.body_part ?? ""),
  eIdx.get(r.equipment ?? ""),
  mIdx.get(r.target ?? ""),
  (r.secondary_muscles ?? []).map((m) => mIdx.get(m)),
  // Upstream `media_id` is only the hash half of the filename; the files are
  // named `<id>-<hash>.jpg` / `.gif`. Store the full basename, which is what
  // CatalogExercise.mediaId is documented to hold and what the URL builders
  // in catalogSource.ts append an extension to.
  r.media_id ? `${r.id}-${r.media_id}` : "",
]);

const payload = JSON.stringify({ b: bodyParts, e: equipment, m: muscles, x: rows });

writeFileSync(
  "src/data/catalogIndex.ts",
  `// GENERATED by scripts/build-catalog.mjs — do not edit by hand.\n` +
    `// Source: https://github.com/hasaneyldrm/exercises-dataset (data licensed MIT).\n` +
    `// See NOTICE.md for the upstream copyright notice.\n\n` +
    `export const CATALOG_COUNT = ${rows.length};\n\n` +
    `/** Column-encoded index; decoded once by catalogService.loadIndex(). */\n` +
    `export const CATALOG_INDEX_JSON = ${JSON.stringify(payload)};\n`
);

const descriptions = JSON.stringify(
  Object.fromEntries(
    records.map((r) => [r.id, (r.instructions?.en ?? "").trim()]).filter(([, text]) => text)
  )
);

writeFileSync(
  "src/data/catalogDescriptions.ts",
  `// GENERATED by scripts/build-catalog.mjs \u2014 do not edit by hand.\n` +
    `// Source: https://github.com/hasaneyldrm/exercises-dataset (data licensed MIT).\n` +
    `// See NOTICE.md for the upstream copyright notice.\n\n` +
    `/** English instructions keyed by exercise id; parsed once on first use. */\n` +
    `export const CATALOG_DESCRIPTIONS_JSON = ${JSON.stringify(descriptions)};\n`
);

console.log(
  `index: ${rows.length} exercises, ${(payload.length / 1024).toFixed(0)} KB | ` +
    `descriptions: ${(descriptions.length / 1024).toFixed(0)} KB`
);
